### ISSUE TITLE
miniBeautifier

### ISSUE THREAD

**Issue by yckart** [xem/miniMinifier#1]
What do you think about the same thing, except to beautify the css?

**Comment by xem** [comment]
Hi, and thanks for your interest (v0.9 is coming soon btw!)
I thought about many things, even HTML and JS minifiers (you can see them in the branch orher-minifiers), but indeed, a css prettifier could be a nice feature!
However, to do it, I'd need to choose a style for the code, or propose many styles, like http://procssor.com...
"Beautiful css code" is so subjective, that would complexify the task.
Do you have an idea (or a need) in particular?

**Comment by xem** [comment]
Hello,
I just released v.0.9, with an experimental beautifier. Hope you like it.

**Comment by yckart** [comment]
Damn, good job! Looks really sweet so far! :ghost:
